[HER-144]  Configure filters behaviour
nerds-sh/hermes.web pull request #47
Opened 2021-08-20 12:19 UTC by ConstantinescuAndrei

## Description
-add formik and yup validation
-store filters value inside formik 
-trigger getDetections when filters button is pressed

## Related
[HER-144](https://nerds-interns.atlassian.net/jira/software/projects/HER/boards/1?selectedIssue=HER-144)

2021-08-24 07:55 UTC, miutamihai requested changes

2021-08-24 07:55 UTC, miutamihai commented on package.json
> +    "formik": "^2.2.9",
Let's use fixed package versions here.

2021-08-24 07:55 UTC, miutamihai commented on src/detections/context.js
> +  const formik = useFormik({ ...useSetFormik(pageSize, pageIndex) })
No need for a new object here, since such an object is already returned by a function call.

2021-08-24 07:55 UTC, miutamihai commented on src/detections/filters/accordion-details/cameras/use-create-camera-list.js
> +    setCameraVariants(createList(items))
Shouldn't the function `createList` be part of this `useEffect`'s dependencies?

2021-08-24 07:55 UTC, miutamihai commented on src/detections/filters/accordion-details/cameras/use-update-camera-list.js
> +import { useEffect } from 'react'
Let's reorder our imports here.

2021-08-24 07:55 UTC, miutamihai commented on src/detections/filters/accordion-details/cameras/use-update-camera-list.js
> +const updateList = items => Object.entries(items)
Same here.

2021-08-24 07:55 UTC, miutamihai commented on src/detections/filters/accordion-details/class/use-props.js
> +
Why the empty space here? :smile:

2021-08-24 07:55 UTC, miutamihai commented on src/detections/filters/accordion-details/remove-button/use-remove-filter.js
> +  }, [setFilters, filterVariants, setFilterVariants])
Same applies to `useCallback`s.

2021-09-27 08:51 UTC, miutamihai approved these changes

2021-09-27 08:56 UTC, Urzica-Platon-Casian approved these changes

2021-09-27 09:45 UTC, andreea-dumitrascu approved these changes

2021-09-27 09:54 UTC, miutamihai approved these changes

2021-09-27 09:54 UTC, merged